name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # Adjust version as needed
      - name: Build
        run: |
            cd UserManagement
            dotnet restore
            dotnet build --configuration Release

      - name: Publish
        run: |
            cd UserManagement
            dotnet publish -c Release -o publish
      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
      - run: cd UserManagement && dotnet rest
      - run: zip -r publish.zip ./UserManagement/*
      - run: aws lambda update-function-code --function-name=lambda-test  --zip-file=fileb://publish.zip 
